/* GENERATED by .design-sync/ds/gen-entry.mjs — do not hand-edit.
 *
 * The design-system barrel uploaded to claude.ai/design. Brand tiers keep their
 * canonical names; the stock registry tier is re-exported under a `Stock` prefix
 * because both tiers export the same 42 names and the bundle is a flat namespace.
 */

// ── Brand recipes — src/components/ui/ (the after)
export { Badge } from "./../../src/components/ui/badge";
export { buttonVariants } from "./../../src/components/ui/button-variants";
export { Button } from "./../../src/components/ui/button";
export { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./../../src/components/ui/card";
export { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSeparator, FieldSet, FieldTitle } from "./../../src/components/ui/field";
export { Input } from "./../../src/components/ui/input";
export { Item, ItemActions, ItemContent, ItemDescription, ItemFooter, ItemGroup, ItemHeader, ItemMedia, ItemSeparator, ItemTitle } from "./../../src/components/ui/item";
export { Label } from "./../../src/components/ui/label";
export { NativeSelect } from "./../../src/components/ui/native-select";
export { Separator } from "./../../src/components/ui/separator";
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "./../../src/components/ui/table";
export { Textarea } from "./../../src/components/ui/textarea";

// ── Brand compositions — src/components/patterns/
export { PageHero } from "./../../src/components/patterns/PageHero";
export { Reveal } from "./../../src/components/patterns/Reveal";
export { TextBand } from "./../../src/components/patterns/TextBand";

// ── Domain components — src/components/ (route-owned)
export { AppointmentForm } from "./../../src/components/AppointmentForm";
export { ArticleBody } from "./../../src/components/ArticleBody";
export { DocumentList } from "./../../src/components/DocumentList";
export { Footer } from "./../../src/components/Footer";
export { Header } from "./../../src/components/Header";
export { HoursTable } from "./../../src/components/HoursTable";
export { JsonLd } from "./../../src/components/JsonLd";
export { LanguageChooser } from "./../../src/components/LanguageChooser";
export { LocationCards } from "./../../src/components/LocationCards";
export { LocationMaps } from "./../../src/components/LocationMaps";
export { NoticeBanner } from "./../../src/components/NoticeBanner";
export { PrepBody } from "./../../src/components/PrepBody";
export { PrintButton } from "./../../src/components/PrintButton";
export { ProfileCardViewer } from "./../../src/components/ProfileCardViewer";
export { TestimonialRail } from "./../../src/components/TestimonialRail";
export { Activity, ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardCheck, Clock, Download, ExternalLink, Facebook, FileText, Globe, Heart, Home, LogOut, Mail, MapPin, Maximize, Menu, MessageSquare, Phone, Printer, Settings, Star, Users, X, ZoomIn, ZoomOut } from "./../../src/components/icons";

// ── Registry, byte-exact — src/components/stock/ (the before)
export { Accordion as StockAccordion, AccordionContent as StockAccordionContent, AccordionItem as StockAccordionItem, AccordionTrigger as StockAccordionTrigger } from "./../../src/components/stock/accordion";
export { AlertDialog as StockAlertDialog, AlertDialogAction as StockAlertDialogAction, AlertDialogCancel as StockAlertDialogCancel, AlertDialogContent as StockAlertDialogContent, AlertDialogDescription as StockAlertDialogDescription, AlertDialogFooter as StockAlertDialogFooter, AlertDialogHeader as StockAlertDialogHeader, AlertDialogMedia as StockAlertDialogMedia, AlertDialogOverlay as StockAlertDialogOverlay, AlertDialogPortal as StockAlertDialogPortal, AlertDialogTitle as StockAlertDialogTitle, AlertDialogTrigger as StockAlertDialogTrigger } from "./../../src/components/stock/alert-dialog";
export { Alert as StockAlert, AlertAction as StockAlertAction, AlertDescription as StockAlertDescription, AlertTitle as StockAlertTitle } from "./../../src/components/stock/alert";
export { AspectRatio as StockAspectRatio } from "./../../src/components/stock/aspect-ratio";
export { Attachment as StockAttachment, AttachmentAction as StockAttachmentAction, AttachmentActions as StockAttachmentActions, AttachmentContent as StockAttachmentContent, AttachmentDescription as StockAttachmentDescription, AttachmentGroup as StockAttachmentGroup, AttachmentMedia as StockAttachmentMedia, AttachmentTitle as StockAttachmentTitle, AttachmentTrigger as StockAttachmentTrigger } from "./../../src/components/stock/attachment";
export { Avatar as StockAvatar, AvatarBadge as StockAvatarBadge, AvatarFallback as StockAvatarFallback, AvatarGroup as StockAvatarGroup, AvatarGroupCount as StockAvatarGroupCount, AvatarImage as StockAvatarImage } from "./../../src/components/stock/avatar";
export { Badge as StockBadge, badgeVariants as stockBadgeVariants } from "./../../src/components/stock/badge";
export { Breadcrumb as StockBreadcrumb, BreadcrumbEllipsis as StockBreadcrumbEllipsis, BreadcrumbItem as StockBreadcrumbItem, BreadcrumbLink as StockBreadcrumbLink, BreadcrumbList as StockBreadcrumbList, BreadcrumbPage as StockBreadcrumbPage, BreadcrumbSeparator as StockBreadcrumbSeparator } from "./../../src/components/stock/breadcrumb";
export { Bubble as StockBubble, BubbleContent as StockBubbleContent, BubbleGroup as StockBubbleGroup, BubbleReactions as StockBubbleReactions } from "./../../src/components/stock/bubble";
export { ButtonGroup as StockButtonGroup, ButtonGroupSeparator as StockButtonGroupSeparator, ButtonGroupText as StockButtonGroupText, buttonGroupVariants as stockButtonGroupVariants } from "./../../src/components/stock/button-group";
export { Button as StockButton, buttonVariants as stockButtonVariants } from "./../../src/components/stock/button";
export { Calendar as StockCalendar, CalendarDayButton as StockCalendarDayButton } from "./../../src/components/stock/calendar";
export { Card as StockCard, CardAction as StockCardAction, CardContent as StockCardContent, CardDescription as StockCardDescription, CardFooter as StockCardFooter, CardHeader as StockCardHeader, CardTitle as StockCardTitle } from "./../../src/components/stock/card";
export { Carousel as StockCarousel, CarouselContent as StockCarouselContent, CarouselItem as StockCarouselItem, CarouselNext as StockCarouselNext, CarouselPrevious as StockCarouselPrevious, useCarousel as stockUseCarousel } from "./../../src/components/stock/carousel";
export type { CarouselApi as StockCarouselApi } from "./../../src/components/stock/carousel";
export { ChartContainer as StockChartContainer, ChartLegend as StockChartLegend, ChartLegendContent as StockChartLegendContent, ChartStyle as StockChartStyle, ChartTooltip as StockChartTooltip, ChartTooltipContent as StockChartTooltipContent } from "./../../src/components/stock/chart";
export type { ChartConfig as StockChartConfig } from "./../../src/components/stock/chart";
export { Checkbox as StockCheckbox } from "./../../src/components/stock/checkbox";
export { Collapsible as StockCollapsible, CollapsibleContent as StockCollapsibleContent, CollapsibleTrigger as StockCollapsibleTrigger } from "./../../src/components/stock/collapsible";
export { Combobox as StockCombobox, ComboboxChip as StockComboboxChip, ComboboxChips as StockComboboxChips, ComboboxChipsInput as StockComboboxChipsInput, ComboboxCollection as StockComboboxCollection, ComboboxContent as StockComboboxContent, ComboboxEmpty as StockComboboxEmpty, ComboboxGroup as StockComboboxGroup, ComboboxInput as StockComboboxInput, ComboboxItem as StockComboboxItem, ComboboxLabel as StockComboboxLabel, ComboboxList as StockComboboxList, ComboboxSeparator as StockComboboxSeparator, ComboboxTrigger as StockComboboxTrigger, ComboboxValue as StockComboboxValue, useComboboxAnchor as stockUseComboboxAnchor } from "./../../src/components/stock/combobox";
export { Command as StockCommand, CommandDialog as StockCommandDialog, CommandEmpty as StockCommandEmpty, CommandGroup as StockCommandGroup, CommandInput as StockCommandInput, CommandItem as StockCommandItem, CommandList as StockCommandList, CommandSeparator as StockCommandSeparator, CommandShortcut as StockCommandShortcut } from "./../../src/components/stock/command";
export { ContextMenu as StockContextMenu, ContextMenuCheckboxItem as StockContextMenuCheckboxItem, ContextMenuContent as StockContextMenuContent, ContextMenuGroup as StockContextMenuGroup, ContextMenuItem as StockContextMenuItem, ContextMenuLabel as StockContextMenuLabel, ContextMenuPortal as StockContextMenuPortal, ContextMenuRadioGroup as StockContextMenuRadioGroup, ContextMenuRadioItem as StockContextMenuRadioItem, ContextMenuSeparator as StockContextMenuSeparator, ContextMenuShortcut as StockContextMenuShortcut, ContextMenuSub as StockContextMenuSub, ContextMenuSubContent as StockContextMenuSubContent, ContextMenuSubTrigger as StockContextMenuSubTrigger, ContextMenuTrigger as StockContextMenuTrigger } from "./../../src/components/stock/context-menu";
export { Dialog as StockDialog, DialogClose as StockDialogClose, DialogContent as StockDialogContent, DialogDescription as StockDialogDescription, DialogFooter as StockDialogFooter, DialogHeader as StockDialogHeader, DialogOverlay as StockDialogOverlay, DialogPortal as StockDialogPortal, DialogTitle as StockDialogTitle, DialogTrigger as StockDialogTrigger } from "./../../src/components/stock/dialog";
export { DirectionProvider as StockDirectionProvider, useDirection as stockUseDirection } from "./../../src/components/stock/direction";
export { Drawer as StockDrawer, DrawerClose as StockDrawerClose, DrawerContent as StockDrawerContent, DrawerDescription as StockDrawerDescription, DrawerFooter as StockDrawerFooter, DrawerHeader as StockDrawerHeader, DrawerOverlay as StockDrawerOverlay, DrawerPortal as StockDrawerPortal, DrawerSwipeHandle as StockDrawerSwipeHandle, DrawerTitle as StockDrawerTitle, DrawerTrigger as StockDrawerTrigger } from "./../../src/components/stock/drawer";
export { DropdownMenu as StockDropdownMenu, DropdownMenuCheckboxItem as StockDropdownMenuCheckboxItem, DropdownMenuContent as StockDropdownMenuContent, DropdownMenuGroup as StockDropdownMenuGroup, DropdownMenuItem as StockDropdownMenuItem, DropdownMenuLabel as StockDropdownMenuLabel, DropdownMenuPortal as StockDropdownMenuPortal, DropdownMenuRadioGroup as StockDropdownMenuRadioGroup, DropdownMenuRadioItem as StockDropdownMenuRadioItem, DropdownMenuSeparator as StockDropdownMenuSeparator, DropdownMenuShortcut as StockDropdownMenuShortcut, DropdownMenuSub as StockDropdownMenuSub, DropdownMenuSubContent as StockDropdownMenuSubContent, DropdownMenuSubTrigger as StockDropdownMenuSubTrigger, DropdownMenuTrigger as StockDropdownMenuTrigger } from "./../../src/components/stock/dropdown-menu";
export { Empty as StockEmpty, EmptyContent as StockEmptyContent, EmptyDescription as StockEmptyDescription, EmptyHeader as StockEmptyHeader, EmptyMedia as StockEmptyMedia, EmptyTitle as StockEmptyTitle } from "./../../src/components/stock/empty";
export { Field as StockField, FieldContent as StockFieldContent, FieldDescription as StockFieldDescription, FieldError as StockFieldError, FieldGroup as StockFieldGroup, FieldLabel as StockFieldLabel, FieldLegend as StockFieldLegend, FieldSeparator as StockFieldSeparator, FieldSet as StockFieldSet, FieldTitle as StockFieldTitle } from "./../../src/components/stock/field";
export { HoverCard as StockHoverCard, HoverCardContent as StockHoverCardContent, HoverCardTrigger as StockHoverCardTrigger } from "./../../src/components/stock/hover-card";
export { InputGroup as StockInputGroup, InputGroupAddon as StockInputGroupAddon, InputGroupButton as StockInputGroupButton, InputGroupInput as StockInputGroupInput, InputGroupText as StockInputGroupText, InputGroupTextarea as StockInputGroupTextarea } from "./../../src/components/stock/input-group";
export { InputOTP as StockInputOTP, InputOTPGroup as StockInputOTPGroup, InputOTPSeparator as StockInputOTPSeparator, InputOTPSlot as StockInputOTPSlot } from "./../../src/components/stock/input-otp";
export { Input as StockInput } from "./../../src/components/stock/input";
export { Item as StockItem, ItemActions as StockItemActions, ItemContent as StockItemContent, ItemDescription as StockItemDescription, ItemFooter as StockItemFooter, ItemGroup as StockItemGroup, ItemHeader as StockItemHeader, ItemMedia as StockItemMedia, ItemSeparator as StockItemSeparator, ItemTitle as StockItemTitle } from "./../../src/components/stock/item";
export { Kbd as StockKbd, KbdGroup as StockKbdGroup } from "./../../src/components/stock/kbd";
export { Label as StockLabel } from "./../../src/components/stock/label";
export { Marker as StockMarker, MarkerContent as StockMarkerContent, MarkerIcon as StockMarkerIcon, markerVariants as stockMarkerVariants } from "./../../src/components/stock/marker";
export { Menubar as StockMenubar, MenubarCheckboxItem as StockMenubarCheckboxItem, MenubarContent as StockMenubarContent, MenubarGroup as StockMenubarGroup, MenubarItem as StockMenubarItem, MenubarLabel as StockMenubarLabel, MenubarMenu as StockMenubarMenu, MenubarPortal as StockMenubarPortal, MenubarRadioGroup as StockMenubarRadioGroup, MenubarRadioItem as StockMenubarRadioItem, MenubarSeparator as StockMenubarSeparator, MenubarShortcut as StockMenubarShortcut, MenubarSub as StockMenubarSub, MenubarSubContent as StockMenubarSubContent, MenubarSubTrigger as StockMenubarSubTrigger, MenubarTrigger as StockMenubarTrigger } from "./../../src/components/stock/menubar";
export { MessageScroller as StockMessageScroller, MessageScrollerButton as StockMessageScrollerButton, MessageScrollerContent as StockMessageScrollerContent, MessageScrollerItem as StockMessageScrollerItem, MessageScrollerProvider as StockMessageScrollerProvider, MessageScrollerViewport as StockMessageScrollerViewport, useMessageScroller as stockUseMessageScroller, useMessageScrollerScrollable as stockUseMessageScrollerScrollable, useMessageScrollerVisibility as stockUseMessageScrollerVisibility } from "./../../src/components/stock/message-scroller";
export { Message as StockMessage, MessageAvatar as StockMessageAvatar, MessageContent as StockMessageContent, MessageFooter as StockMessageFooter, MessageGroup as StockMessageGroup, MessageHeader as StockMessageHeader } from "./../../src/components/stock/message";
export { NativeSelect as StockNativeSelect, NativeSelectOptGroup as StockNativeSelectOptGroup, NativeSelectOption as StockNativeSelectOption } from "./../../src/components/stock/native-select";
export { NavigationMenu as StockNavigationMenu, NavigationMenuContent as StockNavigationMenuContent, NavigationMenuIndicator as StockNavigationMenuIndicator, NavigationMenuItem as StockNavigationMenuItem, NavigationMenuLink as StockNavigationMenuLink, NavigationMenuList as StockNavigationMenuList, NavigationMenuPositioner as StockNavigationMenuPositioner, NavigationMenuTrigger as StockNavigationMenuTrigger, navigationMenuTriggerStyle as stockNavigationMenuTriggerStyle } from "./../../src/components/stock/navigation-menu";
export { Pagination as StockPagination, PaginationContent as StockPaginationContent, PaginationEllipsis as StockPaginationEllipsis, PaginationItem as StockPaginationItem, PaginationLink as StockPaginationLink, PaginationNext as StockPaginationNext, PaginationPrevious as StockPaginationPrevious } from "./../../src/components/stock/pagination";
export { Popover as StockPopover, PopoverContent as StockPopoverContent, PopoverDescription as StockPopoverDescription, PopoverHeader as StockPopoverHeader, PopoverTitle as StockPopoverTitle, PopoverTrigger as StockPopoverTrigger } from "./../../src/components/stock/popover";
export { Progress as StockProgress, ProgressIndicator as StockProgressIndicator, ProgressLabel as StockProgressLabel, ProgressTrack as StockProgressTrack, ProgressValue as StockProgressValue } from "./../../src/components/stock/progress";
export { Questionnaire as StockQuestionnaire, QuestionnaireActions as StockQuestionnaireActions, QuestionnaireChoice as StockQuestionnaireChoice, QuestionnaireChoiceDescription as StockQuestionnaireChoiceDescription, QuestionnaireChoices as StockQuestionnaireChoices, QuestionnaireDescription as StockQuestionnaireDescription, QuestionnaireError as StockQuestionnaireError, QuestionnaireInput as StockQuestionnaireInput, QuestionnaireItem as StockQuestionnaireItem, QuestionnaireNext as StockQuestionnaireNext, QuestionnairePrevious as StockQuestionnairePrevious, QuestionnaireProgress as StockQuestionnaireProgress, QuestionnaireSkip as StockQuestionnaireSkip, QuestionnaireSubmit as StockQuestionnaireSubmit, QuestionnaireTitle as StockQuestionnaireTitle } from "./../../src/components/stock/questionnaire";
export { RadioGroup as StockRadioGroup, RadioGroupItem as StockRadioGroupItem } from "./../../src/components/stock/radio-group";
export { ResizableHandle as StockResizableHandle, ResizablePanel as StockResizablePanel, ResizablePanelGroup as StockResizablePanelGroup } from "./../../src/components/stock/resizable";
export { ScrollArea as StockScrollArea, ScrollBar as StockScrollBar } from "./../../src/components/stock/scroll-area";
export { Select as StockSelect, SelectContent as StockSelectContent, SelectGroup as StockSelectGroup, SelectItem as StockSelectItem, SelectLabel as StockSelectLabel, SelectScrollDownButton as StockSelectScrollDownButton, SelectScrollUpButton as StockSelectScrollUpButton, SelectSeparator as StockSelectSeparator, SelectTrigger as StockSelectTrigger, SelectValue as StockSelectValue } from "./../../src/components/stock/select";
export { Separator as StockSeparator } from "./../../src/components/stock/separator";
export { Sheet as StockSheet, SheetClose as StockSheetClose, SheetContent as StockSheetContent, SheetDescription as StockSheetDescription, SheetFooter as StockSheetFooter, SheetHeader as StockSheetHeader, SheetTitle as StockSheetTitle, SheetTrigger as StockSheetTrigger } from "./../../src/components/stock/sheet";
export { Sidebar as StockSidebar, SidebarContent as StockSidebarContent, SidebarFooter as StockSidebarFooter, SidebarGroup as StockSidebarGroup, SidebarGroupAction as StockSidebarGroupAction, SidebarGroupContent as StockSidebarGroupContent, SidebarGroupLabel as StockSidebarGroupLabel, SidebarHeader as StockSidebarHeader, SidebarInput as StockSidebarInput, SidebarInset as StockSidebarInset, SidebarMenu as StockSidebarMenu, SidebarMenuAction as StockSidebarMenuAction, SidebarMenuBadge as StockSidebarMenuBadge, SidebarMenuButton as StockSidebarMenuButton, SidebarMenuItem as StockSidebarMenuItem, SidebarMenuSkeleton as StockSidebarMenuSkeleton, SidebarMenuSub as StockSidebarMenuSub, SidebarMenuSubButton as StockSidebarMenuSubButton, SidebarMenuSubItem as StockSidebarMenuSubItem, SidebarProvider as StockSidebarProvider, SidebarRail as StockSidebarRail, SidebarSeparator as StockSidebarSeparator, SidebarTrigger as StockSidebarTrigger, useSidebar as stockUseSidebar } from "./../../src/components/stock/sidebar";
export { Skeleton as StockSkeleton } from "./../../src/components/stock/skeleton";
export { Slider as StockSlider } from "./../../src/components/stock/slider";
export { Toaster as StockSonnerToaster } from "./../../src/components/stock/sonner";
export { Spinner as StockSpinner } from "./../../src/components/stock/spinner";
export { Switch as StockSwitch } from "./../../src/components/stock/switch";
export { Table as StockTable, TableBody as StockTableBody, TableCaption as StockTableCaption, TableCell as StockTableCell, TableFooter as StockTableFooter, TableHead as StockTableHead, TableHeader as StockTableHeader, TableRow as StockTableRow } from "./../../src/components/stock/table";
export { Tabs as StockTabs, TabsContent as StockTabsContent, TabsList as StockTabsList, TabsTrigger as StockTabsTrigger, tabsListVariants as stockTabsListVariants } from "./../../src/components/stock/tabs";
export { Textarea as StockTextarea } from "./../../src/components/stock/textarea";
export { Toast as StockToast, ToastAction as StockToastAction, ToastClose as StockToastClose, ToastContent as StockToastContent, ToastDescription as StockToastDescription, ToastPortal as StockToastPortal, ToastProvider as StockToastProvider, ToastTitle as StockToastTitle, ToastViewport as StockToastViewport, Toaster as StockToaster, createToastManager as stockCreateToastManager, toast as stockToast, useToastManager as stockUseToastManager } from "./../../src/components/stock/toast";
export { ToggleGroup as StockToggleGroup, ToggleGroupItem as StockToggleGroupItem } from "./../../src/components/stock/toggle-group";
export { Toggle as StockToggle, toggleVariants as stockToggleVariants } from "./../../src/components/stock/toggle";
export { Tooltip as StockTooltip, TooltipContent as StockTooltipContent, TooltipProvider as StockTooltipProvider, TooltipTrigger as StockTooltipTrigger } from "./../../src/components/stock/tooltip";
