#!/usr/bin/env node
/* Vendors the practice's brand webfonts for the design bundle.
 *
 * In the app these come from next/font/google, which injects --font-lato and
 * --font-trocchi onto <html>. The uploaded bundle never runs next/font, so
 * globals.css's `--font-display: var(--font-trocchi), Georgia, serif` would
 * fall through to Georgia and EVERY design built with this system would render
 * in the wrong face. This script downloads the same families (both OFL) and
 * writes a self-contained fonts.css that defines the variables.
 *
 * Scope note: only the EN/ES pairing is vendored. src/lib/fonts.ts also loads
 * Aleo, Be Vietnam Pro, and four Noto families for the vi/ko/ar locales; those
 * are locale fallbacks the design agent has no way to exercise. See
 * .design-sync/NOTES.md.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DS = dirname(fileURLToPath(import.meta.url));
const OUT = join(DS, 'fonts');

// A modern desktop UA is what makes the API serve woff2 + latin subsets.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { css: 'Lato:wght@400;700;900', slug: 'lato' },
  { css: 'Trocchi', slug: 'trocchi' },
];

mkdirSync(OUT, { recursive: true });

let out = `/* Brand webfonts for the claude.ai/design bundle.
   Generated by .design-sync/ds/fetch-fonts.mjs — do not hand-edit.

   next/font never runs here, so these definitions stand in for the variables
   it would otherwise inject on <html>. Lato and Trocchi are both SIL OFL 1.1;
   the files below are the Google Fonts latin subsets. */

`;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) {
    console.error(`[FONT_FETCH] ${fam.css}: HTTP ${res.status}`);
    process.exit(1);
  }
  let css = await res.text();

  // Keep only the latin subsets — the API emits latin-ext/vietnamese too and
  // the extra ranges are dead weight in a bundle that renders English cards.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
    .filter(([, subset]) => subset === 'latin');
  if (!blocks.length) {
    console.error(`[FONT_FETCH] ${fam.css}: no latin @font-face blocks found`);
    process.exit(1);
  }

  let n = 0;
  for (const [, , face] of blocks) {
    const src = /url\((https:[^)]+\.woff2)\)/.exec(face);
    const weight = /font-weight:\s*(\d+)/.exec(face)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(face)?.[1] ?? 'normal';
    if (!src) continue;
    const file = `${fam.slug}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`;
    const bin = await fetch(src[1], { headers: { 'User-Agent': UA } });
    writeFileSync(join(OUT, file), Buffer.from(await bin.arrayBuffer()));
    out +=
      face
        .replace(/url\(https:[^)]+\.woff2\)/, `url("./${file}")`)
        .replace(/\s+/g, ' ')
        .replace('@font-face {', '@font-face {\n ')
        .replace(/; /g, ';\n ')
        .replace(/ \}$/, '\n}') + '\n\n';
    n++;
  }
  console.error(`  ${fam.slug}: ${n} face(s)`);
}

// NB: only @font-face rules belong in this file — it is consumed by the
// converter's cfg.extraFonts parser, which copies the referenced woff2 into the
// bundle's fonts/ dir. The --font-lato / --font-trocchi variables that
// globals.css reads are declared in tailwind-entry.css instead, so they travel
// through the compiled stylesheet rather than this parsed one.
writeFileSync(join(OUT, 'fonts.css'), out);
console.error(`  wrote ${join('fonts', 'fonts.css')}`);
