#!/usr/bin/env node
// Generates .design-sync/ds/entry.ts — the design-system barrel the converter
// bundles into window.WestchaseGi.
//
// Why this file exists: src/components/ui/ and src/components/stock/ export the
// SAME 42 names (Button, Card, Field, Table, …). The bundle is a flat namespace,
// and a plain `export * from` of both tiers makes ES module semantics DROP every
// ambiguous name silently — the brand tier would vanish with no error. So the
// brand tier keeps canonical names and the stock tier is re-exported under a
// `Stock` prefix (DESIGN.md "Component tiers": stock is the before, ui is the
// after).
//
// Run via `node .design-sync/ds/build-ds.mjs`; regenerate whenever
// `npm run ds:stock` re-vendors the registry or a component is added.

import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Project, Node, ts } from '../../.ds-sync/node_modules/ts-morph/dist/ts-morph.js';

const DS_DIR = dirname(fileURLToPath(import.meta.url));
const REPO = join(DS_DIR, '..', '..');
const C = join(REPO, 'src', 'components');

// Tier definitions. `prefix` is what disambiguates stock from brand.
const TIERS = [
  { name: 'ui', dir: join(C, 'ui'), prefix: '', label: 'Brand recipes — src/components/ui/ (the after)' },
  { name: 'patterns', dir: join(C, 'patterns'), prefix: '', label: 'Brand compositions — src/components/patterns/' },
  { name: 'domain', dir: C, prefix: '', label: 'Domain components — src/components/ (route-owned)' },
  { name: 'stock', dir: join(C, 'stock'), prefix: 'Stock', label: 'Registry, byte-exact — src/components/stock/ (the before)' },
];

// Files that are helpers, not part of the shipped surface.
const SKIP_FILES = new Set(['output-feedback.ts', 'reveal-delay.ts', 'example.tsx']);

// Genuine duplicate names WITHIN a tier — upstream ships two different
// components under one name, so the prefix alone can't separate them.
// Keyed by repo-relative path.
const RENAME = {
  // The registry ships two Toasters: the Base UI one in toast.tsx and the
  // sonner-backed one here. toast.tsx keeps the plain StockToaster name.
  'src/components/stock/sonner.tsx': { Toaster: 'StockSonnerToaster' },
};

const project = new Project({
  skipAddingFilesFromTsConfig: true,
  compilerOptions: { jsx: ts.JsxEmit.Preserve, allowJs: true, skipLibCheck: true },
});

/** All exported names in `file`, split into values and types. */
function exportsOf(file) {
  const sf = project.addSourceFileAtPath(file);
  const values = [];
  const types = [];
  for (const [name, decls] of sf.getExportedDeclarations()) {
    if (name === 'default') continue;
    const isType = decls.every(
      (d) => Node.isInterfaceDeclaration(d) || Node.isTypeAliasDeclaration(d),
    );
    (isType ? types : values).push(name);
  }
  return { values: values.sort(), types: types.sort() };
}

function filesIn(dir, { recurse = false } = {}) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .flatMap((e) => {
      if (e.isDirectory()) return recurse ? filesIn(join(dir, e.name), { recurse }) : [];
      if (!/\.(tsx|ts)$/.test(e.name) || /\.(test|spec|stories)\./.test(e.name)) return [];
      if (SKIP_FILES.has(e.name) || e.name.endsWith('.d.ts')) return [];
      return [join(dir, e.name)];
    })
    .sort();
}

const lines = [
  '/* GENERATED by .design-sync/ds/gen-entry.mjs — do not hand-edit.',
  ' *',
  ' * The design-system barrel uploaded to claude.ai/design. Brand tiers keep their',
  ' * canonical names; the stock registry tier is re-exported under a `Stock` prefix',
  ' * because both tiers export the same 42 names and the bundle is a flat namespace.',
  ' */',
  '',
];

const claimed = new Map(); // exported name -> source file, for collision detection
const collisions = [];
const summary = [];
const aliasByFile = {};
const families = []; // {tier, file, root, members} — one entry per component family

// PascalCase word split, matching how design-sync's partitionSubcomponents
// tokenizes names: `StockInputOTPGroup` -> Stock|Input|O|T|P|Group.
const parts = (n) => n.match(/[A-Z][a-z0-9]*/g) ?? [];
const isPrefix = (a, b) => a.length < b.length && a.every((p, i) => p === b[i]);

/* Pick the family root among a file's exports.
 *
 * shadcn ships flat named exports (CardHeader, not Card.Header), so nothing in
 * the .d.ts says CardHeader belongs to Card — the converter would emit 444 flat
 * cards. The repo's own tier contract does say it: one registry item per file
 * (stock/README.md, MANIFEST.json). So the root is the export whose PascalCase
 * words prefix the most siblings; anything it doesn't cover stays its own root
 * (toast.tsx legitimately ships both Toast and Toaster). */
function pickRoot(names) {
  let best = null;
  for (const c of names) {
    const cp = parts(c);
    const covered = names.filter((o) => o !== c && isPrefix(cp, parts(o)));
    if (!covered.length) continue;
    if (!best || covered.length > best.covered.length ||
        (covered.length === best.covered.length && cp.length < parts(best.root).length)) {
      best = { root: c, covered };
    }
  }
  return best;
}

for (const tier of TIERS) {
  const files = filesIn(tier.dir);
  const emitted = [];
  for (const file of files) {
    const rel = './' + relative(DS_DIR, file).split('\\').join('/').replace(/\.tsx?$/, '');
    const { values, types } = exportsOf(file);
    if (!values.length && !types.length) continue;

    // Prefix while PRESERVING the leading case: `Toast` -> `StockToast`,
    // `toast` -> `stockToast`. Uppercasing both would collapse the pair,
    // and the camelCase exports (buttonVariants, toast) are real API.
    const overrides = RENAME[relative(REPO, file).split('\\').join('/')] ?? {};
    const alias = (n) => {
      if (overrides[n]) return overrides[n];
      if (!tier.prefix) return n;
      return /^[A-Z]/.test(n)
        ? tier.prefix + n
        : tier.prefix.toLowerCase() + n[0].toUpperCase() + n.slice(1);
    };

    for (const n of [...values, ...types]) {
      const a = alias(n);
      if (claimed.has(a)) collisions.push(`${a}: ${relative(REPO, claimed.get(a))} vs ${relative(REPO, file)}`);
      else claimed.set(a, file);
    }

    // Record the family so the converter can nest subcomponents under it.
    const valueAliases = values.map(alias).filter((n) => /^[A-Z]/.test(n));
    const picked = pickRoot(valueAliases);
    families.push({
      tier: tier.name,
      file: relative(REPO, file).split('\\').join('/'),
      root: picked?.root ?? null,
      members: picked ? picked.covered.slice().sort() : [],
      orphans: valueAliases.filter((n) => n !== picked?.root && !picked?.covered.includes(n)).sort(),
    });

    aliasByFile[relative(REPO, file).split('\\').join('/')] =
      Object.fromEntries([...values, ...types].map((n) => [n, alias(n)]));

    const spec = (n) => (tier.prefix ? `${n} as ${alias(n)}` : n);
    if (values.length) {
      emitted.push(`export { ${values.map(spec).join(', ')} } from ${JSON.stringify(rel)};`);
    }
    if (types.length) {
      emitted.push(`export type { ${types.map(spec).join(', ')} } from ${JSON.stringify(rel)};`);
    }
  }
  if (emitted.length) {
    lines.push(`// ── ${tier.label}`, ...emitted, '');
  }
  summary.push(`${tier.name}: ${files.length} files`);
}

if (collisions.length) {
  console.error('[COLLISION] duplicate export names after aliasing:');
  for (const c of collisions) console.error('  ' + c);
  process.exit(1);
}

writeFileSync(join(DS_DIR, 'entry.ts'), lines.join('\n'));

// compounds.json feeds .design-sync/overrides/dts.mjs (cfg.libOverrides), which
// merges it into the compound map the converter derives from the .d.ts. Shape
// matches design-sync's own: {Root: [suffix, …]}, suffix = child words minus
// root words. families.json carries the same data plus tier/file for gen-docs.
const compounds = {};
for (const f of families) {
  if (!f.root || !f.members.length) continue;
  compounds[f.root] = f.members.map((m) => parts(m).slice(parts(f.root).length).join(''));
}
writeFileSync(join(DS_DIR, 'compounds.json'), JSON.stringify(compounds, null, 2) + '\n');
writeFileSync(join(DS_DIR, 'families.json'), JSON.stringify(families, null, 2) + '\n');

// aliases.json: source file -> {localName: exportedName}. port-examples.mjs
// uses it to rewrite the vendored registry demos onto the prefixed exports
// without touching a line of their JSX.
writeFileSync(join(DS_DIR, 'aliases.json'), JSON.stringify(aliasByFile, null, 2) + '\n');

const roots = families.filter((f) => f.root).length;
const nested = Object.values(compounds).reduce((n, m) => n + m.length, 0);
console.error(
  `  entry.ts: ${claimed.size} exports (${summary.join(', ')})\n` +
    `  families: ${roots} roots, ${nested} nested subcomponents`,
);
