/* Vocabulary for the demo dataset. Every person, address and phone number it produces is
   invented. Staff-authored text (notes, staff-entered request messages, clinical notes) never
   assumes a patient's gender; patient-written messages may name their own relatives. */

export const NAME_CLUSTERS = [
  {
    key: "hispanic",
    weight: 28,
    first: [
      "María",
      "José",
      "Carmen",
      "Luis",
      "Ana",
      "Carlos",
      "Rosa",
      "Miguel",
      "Isabel",
      "Jorge",
      "Lucía",
      "Rafael",
      "Elena",
      "Gabriela",
      "Fernando",
      "Daniela",
      "Alejandro",
      "Marisol",
      "Eduardo",
      "Yolanda",
      "Héctor",
      "Beatriz",
      "Raúl",
      "Adriana",
      "Mario",
      "Silvia",
      "Ernesto",
      "Paola",
      "Andrés",
      "Graciela",
      "Javier",
      "Lourdes",
      "Ramón",
      "Teresa",
      "Víctor",
      "Claudia",
      "Orlando",
      "Mercedes",
      "Julio",
      "Natalia",
      "Sergio",
      "Valeria",
      "Diego",
      "Camila",
    ],
    last: [
      "García",
      "Rodríguez",
      "Martínez",
      "Hernández",
      "López",
      "González",
      "Pérez",
      "Sánchez",
      "Ramírez",
      "Torres",
      "Flores",
      "Rivera",
      "Gómez",
      "Díaz",
      "Reyes",
      "Morales",
      "Cruz",
      "Ortiz",
      "Gutiérrez",
      "Ramos",
      "Castillo",
      "Vega",
      "Fernández",
      "Delgado",
      "Suárez",
      "Cabrera",
      "Alvarado",
      "Quintero",
      "Rosario",
      "Acosta",
      "Medina",
      "Herrera",
      "Aguilar",
      "Valdés",
      "Navarro",
      "Padilla",
      "Ibarra",
      "Fuentes",
      "Soto",
      "Rojas",
      "Montes",
      "Lugo",
    ],
  },
  {
    key: "anglo",
    weight: 32,
    first: [
      "James",
      "Mary",
      "Robert",
      "Patricia",
      "Michael",
      "Linda",
      "William",
      "Barbara",
      "David",
      "Susan",
      "Richard",
      "Karen",
      "Thomas",
      "Nancy",
      "Charles",
      "Donna",
      "Mark",
      "Sandra",
      "Steven",
      "Deborah",
      "Paul",
      "Sharon",
      "Kenneth",
      "Cynthia",
      "Brian",
      "Kathleen",
      "Gary",
      "Janet",
      "Timothy",
      "Carol",
      "Jeffrey",
      "Diane",
      "Scott",
      "Pamela",
      "Gregory",
      "Rebecca",
      "Matthew",
      "Laura",
      "Andrew",
      "Emily",
      "Joshua",
      "Megan",
      "Ryan",
      "Heather",
      "Kyle",
      "Ashley",
      "Tyler",
      "Lauren",
      "Connor",
      "Hannah",
      "Douglas",
      "Margaret",
      "Wayne",
      "Judith",
    ],
    last: [
      "Smith",
      "Johnson",
      "Miller",
      "Davis",
      "Wilson",
      "Anderson",
      "Taylor",
      "Moore",
      "Thompson",
      "White",
      "Clark",
      "Lewis",
      "Walker",
      "Hall",
      "Allen",
      "Young",
      "King",
      "Wright",
      "Scott",
      "Green",
      "Baker",
      "Adams",
      "Nelson",
      "Hill",
      "Campbell",
      "Mitchell",
      "Roberts",
      "Carter",
      "Phillips",
      "Evans",
      "Turner",
      "Parker",
      "Collins",
      "Edwards",
      "Stewart",
      "Morris",
      "Murphy",
      "Cook",
      "Rogers",
      "Morgan",
      "Cooper",
      "Peterson",
      "Reed",
      "Bailey",
      "Bell",
      "Kelly",
      "Howard",
      "Ward",
      "Sullivan",
      "Brennan",
      "Gallagher",
      "O'Connor",
      "Fitzgerald",
      "McCarthy",
      "Henderson",
      "Jenkins",
      "Perry",
      "Powell",
      "Russell",
      "Hughes",
      "Bennett",
      "Wood",
      "Barnes",
      "Ross",
      "Fisher",
      "Graham",
      "Hayes",
      "Myers",
      "Ford",
      "Hamilton",
      "Wallace",
      "Sheridan",
      "Whitaker",
      "Lindsey",
    ],
  },
  {
    key: "black",
    weight: 14,
    first: [
      "Darnell",
      "Keisha",
      "Andre",
      "Tamika",
      "Marcus",
      "Latoya",
      "Jerome",
      "Terrence",
      "Monique",
      "Reginald",
      "Yvette",
      "Cedric",
      "Denise",
      "Tyrone",
      "Felicia",
      "Malik",
      "Jasmine",
      "Dwayne",
      "Kimberly",
      "Lamar",
      "Tasha",
      "Angela",
      "Darius",
      "Imani",
      "Calvin",
      "Gwendolyn",
      "Isaiah",
      "Aaliyah",
      "Bernard",
      "Loretta",
      "Jamal",
      "Ebony",
    ],
    last: [
      "Washington",
      "Jackson",
      "Robinson",
      "Williams",
      "Brown",
      "Jones",
      "Harris",
      "Thomas",
      "Freeman",
      "Jefferson",
      "Banks",
      "Booker",
      "Glover",
      "Holloway",
      "Simmons",
      "Mosley",
      "Gaines",
      "Dawson",
      "Grant",
      "Pierce",
      "Hampton",
      "Wiggins",
      "Bryant",
      "Coleman",
      "Ellis",
      "Boyd",
      "Merritt",
      "Battle",
    ],
  },
  {
    key: "vietnamese",
    weight: 4,
    first: [
      "Lan",
      "Minh",
      "Hương",
      "Đức",
      "Thủy",
      "Quang",
      "Mai",
      "Khánh",
      "Hải",
      "Ngọc",
      "Tuấn",
      "Vy",
      "Bảo",
      "Thanh",
    ],
    last: [
      "Nguyen",
      "Tran",
      "Le",
      "Pham",
      "Hoang",
      "Vo",
      "Dang",
      "Bui",
      "Do",
      "Huynh",
      "Phan",
      "Truong",
      "Ngo",
      "Ly",
    ],
  },
  {
    key: "south_asian",
    weight: 5,
    first: [
      "Priya",
      "Rajesh",
      "Anjali",
      "Vikram",
      "Sunita",
      "Arjun",
      "Kavita",
      "Sanjay",
      "Deepa",
      "Rahul",
      "Meera",
      "Anil",
      "Neha",
      "Suresh",
      "Pooja",
      "Ravi",
    ],
    last: [
      "Patel",
      "Shah",
      "Desai",
      "Mehta",
      "Reddy",
      "Iyer",
      "Rao",
      "Kumar",
      "Gupta",
      "Joshi",
      "Nair",
      "Pillai",
      "Chopra",
      "Malhotra",
      "Bhatt",
    ],
  },
  {
    key: "arab",
    weight: 3,
    first: [
      "Omar",
      "Layla",
      "Khalid",
      "Yasmin",
      "Tariq",
      "Nadia",
      "Samir",
      "Rania",
      "Hassan",
      "Mariam",
      "Youssef",
      "Dalia",
      "Karim",
      "Huda",
    ],
    last: [
      "Haddad",
      "Khoury",
      "Saleh",
      "Mansour",
      "Nasser",
      "Aziz",
      "Hamdan",
      "Farah",
      "Barakat",
      "Darwish",
      "Habib",
      "Qasim",
    ],
  },
  {
    key: "haitian",
    weight: 4,
    first: [
      "Jean",
      "Marie",
      "Pierre",
      "Rose",
      "Jacques",
      "Nadège",
      "Emmanuel",
      "Guerline",
      "Wilner",
      "Fabienne",
      "Ricot",
      "Mireille",
    ],
    last: [
      "Joseph",
      "Pierre-Louis",
      "Baptiste",
      "Charles",
      "Jean-Baptiste",
      "Dorvil",
      "Célestin",
      "Toussaint",
      "Désir",
      "Augustin",
      "Exantus",
      "Saint-Fleur",
    ],
  },
  {
    key: "italian",
    weight: 3,
    first: [
      "Anthony",
      "Gina",
      "Salvatore",
      "Angela",
      "Vincent",
      "Theresa",
      "Dominic",
      "Francesca",
      "Joseph",
      "Maria",
    ],
    last: [
      "Russo",
      "Romano",
      "Esposito",
      "Bianchi",
      "Marino",
      "Greco",
      "Ricci",
      "Conti",
      "DeLuca",
      "Lombardi",
    ],
  },
  {
    key: "greek",
    weight: 1,
    first: [
      "Nikolaos",
      "Eleni",
      "George",
      "Sophia",
      "Dimitri",
      "Katerina",
      "Konstantinos",
      "Despina",
    ],
    last: ["Papadopoulos", "Pappas", "Georgiou", "Alexiou", "Katsaros", "Stavros", "Nikolaidis"],
  },
  {
    key: "central_european",
    weight: 2,
    first: [
      "Stanley",
      "Dorothy",
      "Peter",
      "Helen",
      "Walter",
      "Irene",
      "Frank",
      "Joanne",
      "Edward",
      "Lorraine",
    ],
    last: [
      "Nowak",
      "Kowalski",
      "Wiśniewski",
      "Lewandowski",
      "Schmidt",
      "Becker",
      "Hoffman",
      "Larsen",
      "Mueller",
      "Novak",
    ],
  },
  {
    key: "korean",
    weight: 1,
    first: [
      "Ji-woo",
      "Min-jun",
      "Hye-jin",
      "Seo-yeon",
      "Jae-won",
      "Eun-ji",
      "Sung-min",
      "Young-hee",
    ],
    last: ["Kim", "Park", "Choi", "Kang", "Yoon", "Jung", "Han", "Shin"],
  },
  {
    key: "chinese",
    weight: 1.5,
    first: ["Wei", "Mei", "Jian", "Xiaoming", "Lihua", "Hao", "Ying", "Jun"],
    last: ["Chen", "Wang", "Liu", "Zhang", "Huang", "Wu", "Lin", "Zhou"],
  },
  {
    key: "filipino",
    weight: 1.5,
    first: [
      "Grace",
      "Joy",
      "Rowena",
      "Ramil",
      "Cristina",
      "Rodel",
      "Jocelyn",
      "Marites",
      "Arnel",
      "Lourdes",
    ],
    last: [
      "Dela Cruz",
      "Bautista",
      "Villanueva",
      "Aquino",
      "Santos",
      "Ocampo",
      "Manalo",
      "Pascual",
      "Tolentino",
    ],
  },
];

/* Conditions drive the visit path and every note. `scope` means the plan includes an
   endoscopy, so a procedure consultation and a results review follow the first visit. */
export const CONDITIONS = {
  gerd: {
    weight: 13,
    ages: [28, 78],
    scope: false,
    label: "GERD",
    hpi: [
      "Heartburn 4–5 nights a week for about four months, worse after late dinners and lying flat. Over-the-counter famotidine helps for a few hours. No dysphagia, weight loss, or black stools.",
      "Burning chest discomfort and sour taste in the mouth, mostly in the morning. Has been taking omeprazole 20 mg on and off for a year. Denies trouble swallowing or vomiting.",
    ],
    assess: "Typical reflux symptoms without alarm features.",
    plan: [
      "Start omeprazole 40 mg daily 30 minutes before breakfast for 8 weeks. Reviewed reflux precautions: no meals within 3 hours of bedtime, elevate head of bed, limit alcohol and late caffeine. Return in 8 weeks; consider EGD if symptoms persist on therapy.",
      "Switch to pantoprazole 40 mg daily before breakfast. Discussed weight loss and meal timing. Follow up in 2 months; EGD if no response.",
    ],
    fu: [
      "Heartburn now 1–2 nights a week on PPI, much improved. No new symptoms. Plan to step down to 20 mg daily and use famotidine as needed. Follow up in 6 months.",
      "Partial response on twice-daily PPI. Still has regurgitation after large meals. Will schedule EGD to evaluate for hiatal hernia and esophagitis.",
    ],
    message: [
      "I've had bad heartburn almost every night for a few months and the store-bought medicine isn't working anymore.",
      "My doctor wants me to see a GI about acid reflux. I'm waking up coughing at night.",
    ],
  },
  screening: {
    weight: 16,
    ages: [45, 75],
    scope: true,
    label: "Colorectal cancer screening",
    hpi: [
      "Referred by primary care for average-risk colorectal cancer screening. No prior colonoscopy. No rectal bleeding, change in bowel habits, or family history of colon cancer.",
      "Due for screening colonoscopy; last exam 10 years ago was normal per patient. Regular bowel movements, no bleeding. Father had colon polyps at 63.",
    ],
    assess: "Due for colorectal cancer screening.",
    plan: [
      "Screening colonoscopy recommended. Reviewed risks, benefits, and alternatives including stool-based testing; patient prefers colonoscopy. Split-dose prep instructions given.",
    ],
    proc: [
      "Pre-procedure visit. Reviewed medications; no anticoagulants. Prep instructions and clear-liquid diet reviewed with patient and driver arrangements confirmed. Colonoscopy scheduled at the endoscopy center.",
    ],
    res: [
      "Colonoscopy: two small tubular adenomas removed from the ascending colon, otherwise normal. Repeat colonoscopy in 7 years. Copy of report given to patient.",
      "Colonoscopy normal to the cecum with good prep. No polyps. Repeat screening in 10 years.",
      "Colonoscopy: one 6 mm sessile serrated lesion removed from the transverse colon. Pathology benign. Repeat in 5 years.",
    ],
    message: [
      "My primary care doctor said I'm due for a colonoscopy. I just turned 45.",
      "I need to schedule a screening colonoscopy. My insurance requires a consult visit first.",
    ],
  },
  ibs: {
    weight: 10,
    ages: [22, 60],
    scope: false,
    label: "Irritable bowel syndrome",
    hpi: [
      "Intermittent crampy lower abdominal pain for over a year, relieved by bowel movements, alternating loose stools and constipation. Worse with stress. No nocturnal symptoms, bleeding, or weight loss.",
      "Bloating and constipation with straining most days for 8 months. Pain improves after bowel movements. Tried fiber with some bloating. No alarm symptoms.",
    ],
    assess:
      "Symptoms consistent with IBS; no alarm features. Basic labs and celiac serology ordered.",
    plan: [
      "Trial of low-FODMAP diet with dietitian handout. Start psyllium daily, dicyclomine 10 mg as needed for cramping. CBC, CMP, tTG-IgA. Return in 6 weeks.",
      "Start linaclotide 145 mcg daily. Increase water intake. Labs ordered. Follow up in 6 weeks to review response.",
    ],
    fu: [
      "Bloating and pain improved about 60% on low-FODMAP diet. Celiac serology negative. Continue current plan, reintroduce foods one group at a time. Follow up in 3 months.",
      "Constipation better on linaclotide, still some bloating. Labs normal. Continue therapy; add peppermint oil capsules. Follow up as needed.",
    ],
    message: [
      "I've been dealing with stomach cramps and bloating for over a year and nothing seems to help.",
      "Constant bloating and constipation. My doctor thinks it might be IBS and referred me.",
    ],
  },
  crohns: {
    weight: 6,
    ages: [20, 55],
    scope: true,
    label: "Crohn's disease",
    hpi: [
      "Known ileocolonic Crohn's disease diagnosed in 2021. Recent flare with 5–6 loose stools daily, right lower quadrant pain, and 6 lb weight loss. Currently on infliximab every 8 weeks.",
      "New to practice, transferring care for Crohn's disease. On vedolizumab infusions every 8 weeks with good control; 1–2 formed stools daily.",
    ],
    assess: "Crohn's disease; assess activity and therapeutic drug levels.",
    plan: [
      "Check CBC, CMP, CRP, fecal calprotectin, and infliximab trough level before next infusion. Colonoscopy to assess mucosal healing. Continue infusions with Juliet in the infusion suite.",
    ],
    proc: [
      "Pre-procedure visit for ileocolonoscopy to assess disease activity. Reviewed prep; infusion schedule unchanged.",
    ],
    res: [
      "Ileocolonoscopy shows mild patchy inflammation in the terminal ileum, improved from prior. Calprotectin 140. Continue current infusion interval; recheck labs in 3 months.",
    ],
    fu: [
      "Doing well on maintenance infusions. 1–2 formed stools daily, no pain. CRP normal. Continue every 8 weeks. Follow up in 4 months.",
      "Mild increase in stool frequency after a viral illness, now resolving. Trough level adequate. No change in therapy.",
    ],
    message: [
      "I have Crohn's disease and just moved to Westchase. I need a new GI to take over my infusions.",
    ],
  },
  uc: {
    weight: 5,
    ages: [20, 65],
    scope: true,
    label: "Ulcerative colitis",
    hpi: [
      "Ulcerative colitis (left-sided) since 2019. On vedolizumab infusions every 8 weeks. Recent urgency and occasional blood after missing a dose during travel.",
      "Pancolitis diagnosed 2017, previously on mesalamine, now on infliximab. Reports 2–3 stools daily without blood.",
    ],
    assess: "Ulcerative colitis, currently mild activity.",
    plan: [
      "Fecal calprotectin, CBC, CMP. Continue infusions every 8 weeks; add mesalamine suppository nightly for 4 weeks. Surveillance colonoscopy due this year.",
    ],
    proc: [
      "Pre-procedure visit for surveillance colonoscopy with biopsies. Prep reviewed; holding mesalamine the day of the procedure.",
    ],
    res: [
      "Surveillance colonoscopy: Mayo 1 changes in the sigmoid, no dysplasia on biopsies. Continue current therapy; repeat surveillance in 2 years.",
    ],
    fu: [
      "Symptoms resolved after suppository course. Infusions well tolerated. Continue every 8 weeks. Follow up in 4 months.",
    ],
    message: [
      "I was diagnosed with ulcerative colitis a few years ago and need to establish care with a new GI.",
    ],
  },
  masld: {
    weight: 8,
    ages: [35, 72],
    scope: false,
    label: "Fatty liver disease (MASLD)",
    hpi: [
      "Referred for mildly elevated liver enzymes (ALT 78, AST 52) found on routine labs. Ultrasound shows hepatic steatosis. Drinks alcohol rarely. Has type 2 diabetes and BMI 34.",
      "Fatty liver seen on CT done for kidney stones. Liver tests mildly abnormal for two years. No history of hepatitis.",
    ],
    assess: "Metabolic dysfunction-associated steatotic liver disease; fibrosis risk to be staged.",
    plan: [
      "Hepatitis panel, ferritin, A1c. FibroScan ordered. Goal 7–10% weight loss over 6–12 months; referral to nutrition. Avoid alcohol. Return after FibroScan.",
    ],
    fu: [
      "FibroScan: CAP 310, stiffness 6.8 kPa (low fibrosis risk). Down 8 lb since last visit. ALT 61. Continue lifestyle plan; repeat labs and FibroScan in 12 months.",
      "Weight stable. Discussed GLP-1 therapy with PCP for diabetes and liver benefit. Recheck liver enzymes in 6 months.",
    ],
    message: [
      "My liver tests came back high and the ultrasound showed fatty liver. My doctor wants a specialist to look at it.",
    ],
  },
  dyspepsia: {
    weight: 6,
    ages: [25, 70],
    scope: true,
    label: "Dyspepsia",
    hpi: [
      "Upper abdominal burning and early fullness for 3 months. H. pylori stool antigen positive at PCP office; completed one course of treatment with persistent symptoms.",
      "Epigastric pain after meals and nausea for 2 months. Takes ibuprofen several times a week for back pain.",
    ],
    assess: "Dyspepsia, possible persistent H. pylori infection or NSAID-related injury.",
    plan: [
      "Stop NSAIDs. Start pantoprazole 40 mg daily. EGD with biopsies to evaluate for ulcer and confirm H. pylori status.",
    ],
    proc: [
      "Pre-procedure visit for EGD. Holding PPI for 2 weeks before procedure for H. pylori testing; famotidine as needed in the meantime.",
    ],
    res: [
      "EGD: mild antral gastritis; biopsies positive for H. pylori. Starting bismuth quadruple therapy for 14 days. Test of cure 4 weeks after completion.",
      "EGD: small non-bleeding antral ulcer, H. pylori negative. Likely NSAID-related. Continue PPI 8 weeks and avoid NSAIDs.",
    ],
    fu: ["Test of cure negative. Symptoms resolved. Stop PPI after taper. Follow up as needed."],
    message: [
      "Stomach pain and nausea after I eat. I tested positive for H. pylori and the antibiotics didn't fix it.",
    ],
  },
  celiac: {
    weight: 3,
    ages: [20, 60],
    scope: true,
    label: "Celiac disease",
    hpi: [
      "Chronic bloating, loose stools, and fatigue. tTG-IgA elevated at 86 U/mL by PCP. Iron is low. Still eating gluten.",
    ],
    assess: "Suspected celiac disease.",
    plan: [
      "EGD with duodenal biopsies while on a gluten-containing diet. Iron studies, vitamin D, B12. Dietitian referral after confirmation.",
    ],
    proc: [
      "Pre-procedure visit for EGD with duodenal biopsies. Reminded to keep eating gluten until the procedure.",
    ],
    res: [
      "Duodenal biopsies show villous atrophy (Marsh 3a), consistent with celiac disease. Start strict gluten-free diet; dietitian referral placed. Repeat tTG in 6 months.",
    ],
    fu: [
      "Four months gluten-free. Bloating and diarrhea resolved, energy improved. tTG trending down. Continue diet; recheck in 6 months.",
    ],
    message: ["My blood test was positive for celiac and I was told I need a scope to confirm."],
  },
  anemia: {
    weight: 5,
    ages: [40, 82],
    scope: true,
    label: "Iron deficiency anemia",
    hpi: [
      "Iron deficiency anemia found on routine labs (Hgb 10.4, ferritin 6). No visible bleeding. Takes daily aspirin. Never had a colonoscopy.",
    ],
    assess: "Iron deficiency anemia; GI source must be excluded.",
    plan: [
      "Bidirectional endoscopy (EGD and colonoscopy). Celiac serology. Start oral iron every other day. Coordinate aspirin hold with cardiology.",
    ],
    proc: [
      "Pre-procedure visit for EGD and colonoscopy. Cardiology cleared aspirin hold for 5 days. Prep reviewed.",
    ],
    res: [
      "EGD showed a 2 cm hiatal hernia with Cameron lesions; colonoscopy with one small polyp removed. Continue iron and PPI. Repeat CBC and ferritin in 8 weeks.",
    ],
    fu: ["Hgb improved to 12.6 on iron. Tolerating PPI. Continue iron 3 more months then recheck."],
    message: ["My bloodwork showed low iron and my doctor wants a GI to check for bleeding."],
  },
  dysphagia: {
    weight: 4,
    ages: [30, 80],
    scope: true,
    label: "Dysphagia",
    hpi: [
      "Food sticking in the lower chest with meat and bread for 6 months, gradually worse. No weight loss. History of reflux.",
    ],
    assess: "Solid-food dysphagia; evaluate for stricture, ring, or eosinophilic esophagitis.",
    plan: [
      "EGD with possible dilation and esophageal biopsies. Soft diet and chew thoroughly until procedure.",
    ],
    proc: [
      "Pre-procedure visit for EGD with possible dilation. Reviewed sedation and post-dilation precautions.",
    ],
    res: [
      "EGD: Schatzki ring dilated to 18 mm; biopsies negative for eosinophilic esophagitis. Swallowing improved after dilation. Continue PPI.",
    ],
    fu: ["No recurrence of food sticking since dilation. Continue PPI. Return if symptoms recur."],
    message: ["Food has been getting stuck when I swallow, especially meat. It's getting worse."],
  },
  barretts: {
    weight: 3,
    ages: [45, 80],
    scope: true,
    label: "Barrett's esophagus",
    hpi: [
      "Barrett's esophagus without dysplasia diagnosed in 2023, due for surveillance EGD. Reflux controlled on omeprazole.",
    ],
    assess: "Non-dysplastic Barrett's esophagus, surveillance due.",
    plan: ["Surveillance EGD with Seattle-protocol biopsies. Continue PPI daily."],
    proc: ["Pre-procedure visit for surveillance EGD. Medications reviewed."],
    res: [
      "Surveillance EGD: 3 cm segment, biopsies without dysplasia. Repeat surveillance in 3–5 years. Continue PPI.",
    ],
    fu: ["Stable on PPI, no new symptoms. Surveillance plan unchanged."],
    message: ["I have Barrett's esophagus and I'm due for my follow-up scope."],
  },
  bleeding: {
    weight: 6,
    ages: [25, 75],
    scope: true,
    label: "Rectal bleeding",
    hpi: [
      "Bright red blood on the toilet paper intermittently for 6 weeks with hard stools. No change in stool caliber or weight loss. No prior colonoscopy.",
    ],
    assess: "Hematochezia, likely hemorrhoidal; colonoscopy indicated given age and duration.",
    plan: [
      "Diagnostic colonoscopy. Fiber supplement and stool softener. Topical hydrocortisone as needed.",
    ],
    proc: [
      "Pre-procedure visit for diagnostic colonoscopy. Prep reviewed; discussed banding if internal hemorrhoids found.",
    ],
    res: [
      "Colonoscopy: grade 2 internal hemorrhoids, otherwise normal. Continue fiber; hemorrhoid banding offered if bleeding persists.",
    ],
    fu: [
      "Bleeding resolved with fiber and stool softener. No further workup needed. Follow up as needed.",
    ],
    message: [
      "I've noticed blood when I go to the bathroom for a few weeks. It's not a lot but it's worrying me.",
    ],
  },
  diverticulitis: {
    weight: 4,
    ages: [40, 80],
    scope: true,
    label: "Diverticulitis",
    hpi: [
      "Recent episode of sigmoid diverticulitis treated with antibiotics in the ER 6 weeks ago (CT confirmed, uncomplicated). Pain resolved. No prior colonoscopy.",
    ],
    assess:
      "Uncomplicated diverticulitis, recovered; colonoscopy recommended to exclude other pathology.",
    plan: [
      "Colonoscopy in 6–8 weeks after the episode. High-fiber diet. Discussed when to seek urgent care for recurrent pain or fever.",
    ],
    proc: [
      "Pre-procedure visit for colonoscopy after diverticulitis. Symptom-free. Prep reviewed.",
    ],
    res: [
      "Colonoscopy: sigmoid diverticulosis, no masses or polyps. High-fiber diet; no routine follow-up needed beyond standard screening.",
    ],
    fu: ["No recurrent episodes. Continue high-fiber diet. Return as needed."],
    message: [
      "I was in the ER for diverticulitis last month and they told me to follow up with GI.",
    ],
  },
  polyps: {
    weight: 6,
    ages: [50, 80],
    scope: true,
    label: "History of colon polyps",
    hpi: [
      "Personal history of adenomatous polyps (3 tubular adenomas in 2021). Due for surveillance colonoscopy. No current GI symptoms.",
    ],
    assess: "Surveillance colonoscopy due for prior adenomas.",
    plan: ["Surveillance colonoscopy. Review anticoagulation; split-dose prep."],
    proc: [
      "Pre-procedure visit for surveillance colonoscopy. Holding apixaban 2 days with cardiology approval.",
    ],
    res: ["Surveillance colonoscopy: one 4 mm tubular adenoma removed. Repeat in 5 years."],
    fu: ["Results reviewed by phone previously; patient doing well. Next surveillance in 5 years."],
    message: ["I'm due for my follow-up colonoscopy. I've had polyps removed before."],
  },
};

export const CANCEL_REASONS = [
  "Patient rescheduled due to a work conflict",
  "Patient ill; will call back to reschedule",
  "Insurance authorization still pending",
  "Patient requested a different provider",
  "Transportation fell through",
  "Provider schedule change",
];

/* Website request messages for people who are not yet patients. */
export const NEW_REQUEST_MESSAGES = {
  en: [
    "I've had stomach pain on and off for about two months, mostly after eating. Mornings work best for me.",
    "My primary care doctor referred me for a colonoscopy. I'm 52 and have never had one.",
    "Looking for a new GI. I have Crohn's and my previous doctor retired.",
    "Heartburn every night even with Prilosec. Can I get in before the end of the month?",
    "I had blood in my stool twice this week. No pain. Please call my cell, I can't answer at work before 3.",
    "My mom (78) needs an appointment for trouble swallowing. I'm her daughter and I handle her appointments; please call me at this number.",
    "Referred for elevated liver enzymes. I have Florida Blue. Do you take it?",
    "Bloating and constipation for months. I've tried everything from the pharmacy.",
    "Need a consult before my colonoscopy. Prefer the Lutz office, it's closer to home.",
    "I was diagnosed with celiac on a blood test and was told I need a scope to confirm.",
    "Follow-up after my ER visit for pancreatitis. Discharge papers say to see GI within 2 weeks.",
    "I'd like a second opinion about my IBS treatment. Afternoons only please.",
  ],
  es: [
    "Tengo acidez y dolor de estómago desde hace varios meses. Prefiero que me llamen en español, por favor.",
    "Mi médico me recomendó hacerme una colonoscopia. Tengo 50 años. Puedo ir en la mañana.",
    "Necesito una cita para mi esposo, tiene sangrado al ir al baño. Él habla poco inglés.",
  ],
  vi: ["Tôi bị đau bụng và đầy hơi nhiều tháng nay. Xin gọi lại cho tôi vào buổi chiều."],
};

export const STAFF_REQUEST_MESSAGES = [
  "Called the front desk. Referred by PCP for reflux that is not responding to omeprazole.",
  "Walk-in at the Tampa office asking for a screening colonoscopy consult. Prefers Thursday mornings.",
  "Family member phoned in to arrange an anemia follow-up and handles scheduling; this number reaches them.",
];

export const CONTACT_NOTES = [
  "Left voicemail with callback number and office hours.",
  "No answer, mailbox full. Will try again tomorrow afternoon.",
  "Spoke briefly — patient was driving. Asked us to call back after 3.",
  "Voicemail left in Spanish per request.",
  "Verified insurance on file is Aetna PPO; referral not required.",
  "Patient asked for the earliest Lutz opening with Dr. Awad.",
  "Waiting on referral and last colonoscopy report from PCP office; faxed request.",
  "Patient wants afternoon appointments only — works early shift.",
  "Number on the form reached a relative, who passed the message along.",
];
